---
title: "Your title"
author: "Your name"
output:
  xaringan::moon_reader:
    css: [useR, useR-fonts]
    lib_dir: libs
---

class: chapter-slide

# Chapter

---

## Header 2

Some text

### Header 3

```{r}
# some code
seq(1:5)
```

---

## Creating some plots

We will use the [viridis](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html) package to create some colorblind-friendly plots. 
Let's see how the graph looks like with various color-vision-deficiency [simulations](https://github.com/clauswilke/colorblindr):

```{r, echo=FALSE, message=FALSE}
library(ggplot2)
library(colorblindr)
library(viridis)

theme_useR <- function(base_size = 28) {
  theme_bw(base_size = base_size) + 
    theme(legend.margin = margin(), legend.title = element_blank())
}
```

```{r}
fig <- ggplot(iris, aes(Sepal.Length, fill = Species)) + 
  geom_density(alpha = 0.7) + theme_useR() + 
  theme(legend.position = c(0.8, 0.9),legend.margin = margin(),
        legend.title = element_blank()) 
fig_grid <- cvd_grid(fig)
```

.center[
```{r,echo=FALSE, fig.show="hold", out.width="40%"}
fig
cvd_grid(ggplot(iris, aes(Sepal.Length, fill = Species)) + 
  geom_density(alpha = 0.7) + theme_useR(base_size = 18) + 
  theme(legend.position = c(0.7, 0.8)) )

```
]

---

Let's use a color scale that works better


```{r}
fig2 <- ggplot(iris, aes(Sepal.Length, fill = Species)) + 
  geom_density(alpha = 0.8) + theme_useR() + 
  theme(legend.position = c(0.8, 0.9))+ 
  scale_fill_viridis(discrete = TRUE)
fig_grid2 <- cvd_grid(fig2)
```


```{r,echo=FALSE, fig.show="hold", out.width="48%"}
fig2
cvd_grid(ggplot(iris, aes(Sepal.Length, fill = Species)) + 
  geom_density(alpha = 0.8) + theme_useR(base_size = 18) + 
  theme(legend.position = c(0.7, 0.8))+ scale_fill_viridis(discrete = TRUE) ) 
```

